apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-15-volume
  namespace: awx
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-15-ansible-awx-postgres-15-0
    namespace: awx
  hostPath:
    path: /data/postgres-15
  persistentVolumeReclaimPolicy: Retain
  storageClassName: awx-postgres-volume
  volumeMode: Filesystem
 