apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-09-15T16:46:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: postgres-15-ansible-awx-postgres-15-0
  namespace: awx
  resourceVersion: "31381"
  uid: b7492e4b-ac3a-470d-b46c-3259d47f1848
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: awx-postgres-volume
  volumeMode: Filesystem
  volumeName: awx-postgres-15-volume
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi